# This file was generated by GoReleaser. DO NOT EDIT.
cask "awless" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "b77464c66cedffeeff0ca3bfe6fa7f050f8357eedf6501a5fd1e0146f4f3195d"
      url "https://github.com/bootswithdefer/awless/releases/download/v#{version}/awless_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5873156982b1798f91d59c86a3c536672418244ac6cdb827681b537bdc27d9a1"
      url "https://github.com/bootswithdefer/awless/releases/download/v#{version}/awless_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a9355b251e9f547f29436070964d2fb28ba14d717bb14536f235c3ab9c930d31"
      url "https://github.com/bootswithdefer/awless/releases/download/v#{version}/awless_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "454a4a05103cef60c256c1dcd6431a0f99e681d48729e74694ed95706ef9769e"
      url "https://github.com/bootswithdefer/awless/releases/download/v#{version}/awless_#{version}_linux_arm64.tar.gz"
    end
  end

  name "awless"
  desc "A powerful CLI to manage AWS, with a template DSL, revertible actions and offline resource graphs"
  homepage "https://github.com/bootswithdefer/awless"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awless"

  postflight do
    if OS.mac?
      system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/awless"
    end
  end

  # No zap stanza required

end
