# This file was generated by GoReleaser. DO NOT EDIT.
cask "awless" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "97b1869d49e789ce28033e9090799533029b45e5c1bd975bd67970d5af97befa"
      url "https://github.com/bootswithdefer/awless/releases/download/v#{version}/awless_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a6ff359276af9f8106a33b341965196ffefeabf46dab19f73986cc1f837baa2c"
      url "https://github.com/bootswithdefer/awless/releases/download/v#{version}/awless_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5bee9e2e66408b83fcc9e972bcdcef211adefcc3b6b062f8ca6f03d3798d9948"
      url "https://github.com/bootswithdefer/awless/releases/download/v#{version}/awless_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6001de804e700ae294f5e61f6c12be58410d11fe20f6fa9d64c5f30709fc2b1c"
      url "https://github.com/bootswithdefer/awless/releases/download/v#{version}/awless_#{version}_linux_arm64.tar.gz"
    end
  end

  name "awless"
  desc "A powerful CLI to manage AWS, with a template DSL, revertible actions and offline resource graphs"
  homepage "https://github.com/bootswithdefer/awless"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awless"

  postflight do
    if OS.mac?
      system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/awless"
    end
  end

  # No zap stanza required

end
