# This file was generated by GoReleaser. DO NOT EDIT.
cask "awless" do
  version "1.4.2"

  on_macos do
    on_intel do
      sha256 "348573fa418b917d86d15fd0a7c0ba5f81ab0e006387fc6de6a4e77e7de8b239"
      url "https://github.com/bootswithdefer/awless/releases/download/v#{version}/awless_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "57d21dd2c2abfad40478603088e97e02667a6410beaf3e468dc4444c37af8ab5"
      url "https://github.com/bootswithdefer/awless/releases/download/v#{version}/awless_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "943105854fc2cca403f33372d8bd030dfc2a9f718b18118328148d0527562ae4"
      url "https://github.com/bootswithdefer/awless/releases/download/v#{version}/awless_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "496d85b8e2c8bd5cefa7dbd97972448d3d96a4e11a8d2d16b851de1931bd7216"
      url "https://github.com/bootswithdefer/awless/releases/download/v#{version}/awless_#{version}_linux_arm64.tar.gz"
    end
  end

  name "awless"
  desc "A powerful CLI to manage AWS, with a template DSL, revertible actions and offline resource graphs"
  homepage "https://github.com/bootswithdefer/awless"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awless"

  postflight_steps do
    on_macos do
      run "xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/awless"]
    end
  end

  # No zap stanza required

end
